#!/bin/python3

import math
import os
import random
import re
import sys
from collections import Counter


if __name__ == '__main__':
    s = input()
    c = Counter(s).most_common()
    s1 = sorted(c, key=lambda x: (-x[-1], x[0]))
    for i in range(3):
        print(s1[i][0], s1[i][1])
